const base = ''
async function j(method, url, body, headers={}){
  const res = await fetch(base+url, { method, headers: { 'content-type':'application/json', ...headers }, body: body?JSON.stringify(body):undefined })
  if(!res.ok) throw new Error(await res.text())
  return res.json()
}
export const health = () => j('GET','/api/health')
export const getQR = (id='main', reset=false) => j('POST','/api/qr',{ id, reset })
export const getCode = (id='main', phone, reset=false) => j('POST','/api/code',{ id, phone, reset })
export const getGroups = () => j('GET','/api/groups')
export const saveGroup = (payload) => j('POST','/api/groups', payload)
export const getEconomyTop = (n=20) => j('GET', `/api/economy/top?n=${encodeURIComponent(n)}`)
export const getAudios = () => j('GET','/api/audios')
export const getEvents = () => j('GET','/api/events')
export const getPets = () => j('GET','/api/pets')
export const upsertAudio = (payload) => j('POST','/api/audios/upsert', payload)
export const deleteAudio = (trigger) => j('POST','/api/audios/delete', { trigger })
export const saveEvents = (payload) => j('POST','/api/events', payload)
export const savePets = (payload) => j('POST','/api/pets', payload)
export const getStickers = () => j('GET','/api/stickers')
export const upsertSticker = (payload) => j('POST','/api/stickers/upsert', payload)
export const deleteSticker = (name) => j('POST','/api/stickers/delete', { name })
export const getCasino = () => j('GET','/api/casino')
export const saveCasino = (payload) => j('POST','/api/casino', payload)
export const getStatus = () => j('GET','/api/status')
export const startBot = () => j('POST','/api/start')
export const stopBot = () => j('POST','/api/stop')
export const getStats = () => j('GET','/api/stats')
export const adminAction = (action, payload, token) => j('POST', `/api/admin/${action}`, payload, token? { Authorization: `Bearer ${token}` } : {})
// IA local
export const aiLocalStatus = () => j('GET','/api/ai/local/status')
export const aiLocalStart = () => j('POST','/api/ai/local/start')
export const aiLocalStop = () => j('POST','/api/ai/local/stop')
export const aiLocalChat = (payload) => j('POST','/api/ai/local/chat', payload)
export const aiGetConfig = () => j('GET','/api/ai/local/config')
export const aiSaveConfig = (payload) => j('POST','/api/ai/local/config', payload)
export const aiOllamaModels = () => j('GET','/api/ai/ollama/models')
